### PR TITLE
Update config-file-reference.md

### PR DESCRIPTION
**Pull request by mauriciogc-sudo**
Adding a NOTE on the "Job file Option Uploads" related to a shared folder.

### CODE REVIEW

**Comment by fdevans** [comment]
@mauriciogc-sudo This needs a bit more clarity and some edits for how it's worded.  Can you provide more details what the goal of this is?

**Comment by mauriciogc-sudo** [comment]
@fdevans Hi, sure. The context is this:
If you have a rundeck cluster, remote execution policy, lb , many jobs with the Upload option file, and those jobs were created on only one cluster member, every time that someone login to rundeck, the lb will connect you to every cluster member, so when you try to upload a file and you are not on the owner member, the upload will fail with an error like "rundeck can not find the file". So, this can be fixed using an nfs on every cluster member, with this shared folder the upload option file will work no matter the lb connected to.
I talked with dev and told me that this is not supported, but works. The idea was to add a note for this if you have a cluster with this configuration.
Makes sense?
We have the customer CGS with this problem. They asked me why does not say anything about this on the docs.

**Comment by fdevans** [comment]
@wayfaringson Can you collaborate with @mauriciogc-sudo  on this?

**Comment by wayfaringson** [comment]
Will do.  Chatted with him earlier and we'll come up with clearer language for this situation.

**Review by wayfaringson — CHANGES_REQUESTED** [review]
How about this @mauriciogc-sudo 

NOTE:
In a clustered mode, it is important to note that this option by default will only upload the file to a single cluster member (whichever server you are uploading the file on).  To address this in a better way, it is recommended that you set the desired path to a directory that is shared across all cluster members.  This could be and NFS share or something like it.  By doing so, when a file is uploaded, it will be available for all cluster members.

**Comment by mauriciogc-sudo** [comment]
@wayfaringson yeah, sounds good, sound better.

Thanks

**Comment by fdevans** [comment]
@mauriciogc-sudo Are you going to update the PR?

**Review by mauriciogc-sudo — COMMENTED** [review]
We changed the Note related to NFS.

**Review by fdevans — APPROVED** [review]

**Comment by fdevans** [comment]
Approving and merging, then will fixup typos since I don't have access to the fork.

**Review by wayfaringson — APPROVED** [review]
Looks good.

**Pull request merged**
