### PR TITLE
Upgrade to Node 18

### PR DESCRIPTION
**Pull request by chrismcg14**

### CODE REVIEW

**Comment by gschueler** [comment]
:eyes: do we not have any CI that builds the docs site for testing?

**Comment by chrismcg14** [comment]
@gschueler I do not think so

**Comment by fdevans** [comment]
No.  There isn't a "test" CI for docs.  When we trigger the build if something fails it doesn't copy the build files to the S3 bucket.  Testing falls to the person updating to ensure their changes work.

**Comment by fdevans** [comment]
Closing as this is being done in a different branch

**Pull request closed without merging**
