### PR TITLE
change values for scm interval and init.delay for the real values on the code

### PR DESCRIPTION
**Pull request by jgarces-pd**
change values for scm interval and init.delay for the real values on the code

### CODE REVIEW

**Comment by jgarces-pd** [comment]
@ronaveva

**Review by fdevans — APPROVED** [review]

**Comment by fdevans** [comment]
I'll approve the text, but someone please confirm this matches the code.
@ronaveva ?

**Comment by ronaveva** [comment]
> I'll approve the text, but someone please confirm this matches the code. @ronaveva ?

The only change should be the default init value from 10 to 0 seconds

**Comment by jgarces-pd** [comment]
@ronaveva @fdevans I changed the values back to 20 Seconds on the interval, and 0 to the init

**Review by ronaveva — APPROVED** [review]
LGTM

**Pull request merged**
