### PR TITLE
Upgrading guide for Rundeck 3.1

### PR DESCRIPTION
**Pull request by gschueler**
WIP:

Please comment with Rundeck 3.1 upgrade guide information: Breakages, configuration changes, install requirements, etc.

### CODE REVIEW

**Comment by sjrd218** [comment]
New configuration: `rundeck.security.requiredRole=required_role`

A user must have the role specified in `rundeck.security.requiredRole` to be able to login if this configuration value is set.

**Comment by ProTip** [comment]
Changes to the Docker image to make it compatible with OpenShift 4+ may break downstream image builds.

**Comment by gschueler** [comment]
@sjrd218 is this something that would break an in-place upgrade? I thought it only was in effect if they add that configuration?

**Comment by gschueler** [comment]
@ProTip can you write those instructions here? or is the description of that PR sufficient?

**Comment by sjrd218** [comment]
@gschueler You are correct. It only checks the value if the configuration is set. Since it won't be set by default it shouldn't break any in-place upgrades. It would only affect people who intentionally add that configuration.

**Comment by gschueler** [comment]
@ProTip i added the docker openshift content, lmk if it needs to change

**Comment by ProTip** [comment]
@gschueler Looks good to me.

**Pull request merged**
