### PR TITLE
added section Reverse Proxy + custom URL + GSSAPI in war config

### PR DESCRIPTION
**Pull request by AndLLA**
Hallo,
first of all, I would like to thank you for the availability of such a wonderful software.

I put together a sort of how-to / tutorial for the installation of rundeck under apache2 reverse proxy, 
with a customized URL path and pre-authentication using GSSAPI.

This how-to collects in one place all the configuration tuning and maybe can ease the life of a new sys-admin.
I think it could be an interesting addition to the installation section related to the "war" method.
The configuration proposed is actively used on our side.

### CODE REVIEW

**Comment by fdevans** [comment]
Hi @AndLLA.  This is great content, but I feel it would be better served in our Learning Section as a Tutorial.  Let me know if you'd like some guidance how to add a new entry over there.

**Review by fdevans — CHANGES_REQUESTED** [review]
see previous comment.  If you need help on how to add to the Learning Section as a How-To let me know.

**Comment by AndLLA** [comment]
Hallo,
sure,
shall I put it under Administration ?
how shall I name it ?
Reverse Proxy + custom URL + GSSAPI ?

Thanks

docs_howto

**Comment by fdevans** [comment]
Administration looks good.
After the changes are staged I'll take a look deeper at the content and help refine the title.

**Pull request merged**
