### PR TITLE
Update runner-advancedsetup.md

### PR DESCRIPTION
**Pull request by jplassnibatt**
Adding runner + paop with self signed.

### CODE REVIEW

**Comment by jplassnibatt** [comment]
BTW, I already tested all the examples.

**Comment by fdevans** [comment]
We typically avoid documenting self-signed cert setups outside of lab builds since it's not considered "secure" by the industry as a whole.  Let's talk about a way we can document this differently to show how it's done without making it look like an official setup doc.

**Review by fdevans — CHANGES_REQUESTED** [review]
see comment on main thread

**Comment by fdevans** [comment]
Closing after discussion with @jplassnibatt.  He will re-implement as a HowTo article

**Pull request closed without merging**
